[package]
name = "opendracli"
version = "0.1.0"
authors = ["GrbavaCigla <alexa.ognjanovic@protonmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.22"
clap = "*"

[dependencies.core]
path = "../core"
